### ISSUE TITLE
Network Configuration going in iptables-legacy instead of iptables

### ISSUE THREAD

**Issue by ashutoshbbpandey** [burmilla/os#77] opened 2021-04-12 03:50 UTC
**BurmillaOS Version: v1.9.1**

Burmilla OS is used as guest OS for vApp, to configure the network configuration using the ovftool at the time of loading, was using rancher earlier, with rancher configuration were going in iptables, with burmilla OS configuration are getting updated in iptables-legacy. Though, post setting alternative of iptables to iptables-legacy it is working.

What got changed from rancher to burmilla, i.e., causing update in iptables-legacy instead iptables?

Instead of setting alternative post installation can it be set at first go itself?

**Comment by olljanat** [comment] 2021-04-12 04:27
We switched Debian as default console and updated it to Buster (10) #9

On that one iptables is marked as legacy because Debian now favor nftables instead of.

Anyway, does this cause some issue(s) on your use cases or are just worry about those warning messages?

What comes to iptables -> nftables migration on v1.9.x versions we try to keep changes on minimum so we most probably will not do it unless there is some very ugly bug(s) and no other way to fix those.

2.0.x versions we most probably should include that change too before first release version as ot good place to do these possible breaking changes. But before that we need investigate that which level that support exist on Docker side as this one haven't been closed moby/moby#26824

**Comment by ashutoshbbpandey** [comment] 2021-04-12 11:24
I package the apps including web-app, having UI to application as vApp. And, Guest OS burmilla OS configured using packer, and taking the IP address dynamically at run time using OVF property, now since, ip information is getting updated in iptables-legacy not able to access the web app installed on vApp

**Comment by olljanat** [comment] 2021-04-12 20:52
Very interesting use case. Looks that I found root cause which is that console is actually now already using iptables-nft (which you can see with command `ls -l /etc/alternatives/iptables`) which is incorrect as rest of the OS is still using iptables-legacy.

I opened pull request #84 about changing it back.

In meantime you can include these commands to your packer script which should fix the issue:
```bash
sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
```

**Comment by ashutoshbbpandey** [comment] 2021-06-17 16:18
Can we achieve it by adding configuration in cloud-config.yml

**Comment by olljanat** [comment] 2021-06-17 16:47
Now it is already easier to use [v1.9.2-rc3](https://github.com/burmilla/os/releases/tag/v1.9.2-rc3) which contains #84

**Comment by ashutoshbbpandey** [comment] 2021-06-17 19:05
Post console updates:
sudo update-alternatives --set iptables /usr/sbin/iptables-legacy
sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy

applied settings are reverted.

**Closed** 2022-07-31 07:16 UTC
Labels: bug, version/v1.9.x
