### ISSUE TITLE
The system boot sample is not the correct one

### ISSUE THREAD

**Issue by tomaswarynyca** [burmilla/os#50] opened 2021-01-21 13:55 UTC
As you can see in the image ros-sysinit keeps throwing messages after requesting the login user
This is confusing for the user when he has to enter the login data.

![photo_2021-01-21_10-33-07](https://user-images.githubusercontent.com/41587659/105357896-3a0c2180-5bd4-11eb-9cd8-26a2845cf99a.jpg)

**Comment by olljanat** [comment] 2021-01-21 15:46
That one can be tricky to fix because afaiu BurmillaOS boot is asynchronous process.

**Comment by h8liu** [comment] 2021-03-04 20:32
imo, this is expected behavior, because system log is printing to tty1. for example if you plugin a usb drive, and trigger more system/kernel events, there will be more logs printing out.

if one finds it annoying, one can switch to tty2 (via Ctrl-Alt-F2), which should be clean.

I would just close this issue.

**Closed** 2024-03-05 12:47 UTC
Labels: enhancement, version/v1.9.x
